### ISSUE TITLE
Wrong instruction about installing the kernel-specification

### ISSUE THREAD

**Issue by ryukinix** [brendan-rius/jupyter-c-kernel#1]
The manual installation has that flow:

```

    git clone git@github.com:brendan-rius/jupyter-c-kernel.git
    pip install jupyter-c-kernel
    cd jupyter-c-kernel
    jupyter-kernelspec install c_kernel

```

I'm ok until `jupyter-kernelspec intall c_kernel`.  The problem is kernelspec are waiting for a `kernel.json` and you passing `c_kernel` whose has the .py files for internal function of kernel, not the specification. That doesn't works here. Beyond that, `jupyter-kernelspec` (at least the version I'm using now [4.1]) only works passing `--user` for user installing or global installing using `sudo`.

I think you need put your kernel.json in other local, maybe, in a isolated folder called `C` or `c_spec`. So that you can put in the instructions some like `jupyter-kernelspec install c_spec --user` and all will be fine.

I tested here and works fine.

By the way, great idea. Thanks for this. Is possible support input for `stdin` too like `scanf` calls? Would be really great.

**Comment by brendan-rius** [comment]
Thank you for the issue.
It should be fixed now, tell me if it works for you.

I also created issue #3 to allow to read from `stdin`

**Comment by ryukinix** [comment]
Nice! Works really fine now! Thanks for that and the fast answer. It's a really cool project and I don't see other similar in the internet. Maybe we can point this later in the [Jupyter-kernels-for-other-languages](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages).

**Comment by brendan-rius** [comment]
Updated! https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages
