### ISSUE TITLE
Installation Steps Ubuntu 16

### ISSUE THREAD

**Issue by msgoff** [brendan-rius/jupyter-c-kernel#18]
Hello, 
Thank you for the great work on this project!
I am new to C, and the time saved in using the notebooks vs compile then run, is very noticeable.
It also makes for a much nicer work flow.

These are the steps I used to install the jupyter-c-kernel.
The only difference is using pip3 and install ipykernel. 
sudo pip3 install jupyter-c-kernel
git clone https://github.com/brendan-rius/jupyter-c-kernel.git
cd jupyter-c-kernel/
jupyter-kernelspec install c_spec/
sudo pip3 install ipykernel
jupyter-notebook

**Comment by brendan-rius** [comment]
Thank you for your contribution! 

I am closing this as this is not really an issue that has to be solved, and also because installation method has changed :)
