### ISSUE TITLE
Unable to download the C code from the cells nor able to identify where compiled files are stored

### ISSUE THREAD

**Issue by VoodooChild83** [brendan-rius/jupyter-c-kernel#23]
I get the following error when attempting to download the C file from the notebook.

`nbconvert failed: FileExtension trait 'file_extension' does not begin with a dot: 'c'`

And I am unable to locate the compiled files. Is the first issue resolvable, and is there a location where the kernel sends the compiled files (as is similarly done for cython and fortran magics)?

**Comment by brendan-rius** [comment]
The problem looks like it is fixed in the new version.
The compiled file are temporary files and cannot easily be viewed. Why do you need them? :)

Please re-open the issue it it does not work after upgrading.
