### ISSUE TITLE
IPKernelApp ERROR

### ISSUE THREAD

**Issue by HunterYIboHu** [brendan-rius/jupyter-c-kernel#25]
OS - windos10
Python version - Python3.5.1

I start the C kernel, but when trying to compile the code like the following example:
```C
#include <stdio.h>

int main() {
    printf("Hello world\n");
}
```
I got this error message under this cell:
```
realgcc.exe: error: unrecognized command line option '-rdynamic'
[C kernel] GCC exited with code 1, the executable will not be executed
```
and another shell that maintain the jupyter notebook show the following error message the same time:
```
realgcc.exe: error: unrecognized command line option '-rdynamic'
[IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: 'comm_open'
```

**Comment by minghu6** [comment]
I have the same problem

**Comment by brendan-rius** [comment]
Hello,

it looks like the version of GCC you are using do not support the rdynamic flag.
What versions are you using?

Could you try updating them?

**Comment by minghu6** [comment]
@brendan-rius It's cygwin gcc.

**Comment by brendan-rius** [comment]
Supporting Windows is a bit a work that I am not willing to do just right now.
If you want to use it on Windows, I would recommend using Docker :)

If you are willing to open a PR to make the project windows-compatible, you are welcome
