### ISSUE TITLE
kernel dies automatically when started

### ISSUE THREAD

**Issue by gauravparashar** [brendan-rius/jupyter-c-kernel#30]
I installed the kernel using the script. 
After that i restarted the server.
I have installed it on jupyterhub for students access. 
Id dies and displays the following message:
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

**Comment by aakhmetz** [comment]
I am sure no one can help you from such minimal amount of information.

**Comment by brendan-rius** [comment]
Closing as there is not enough info to debug.
Please try again with the latest version, and re-open the issue with more info if you still have the problem
