### ISSUE TITLE
gcc compilation flags

### ISSUE THREAD

**Issue by SamKChang** [brendan-rius/jupyter-c-kernel#31]
Great project! I am trying to use fftw3, which requires gcc flag '-lfftw3'. Is it possible to configure compilation flags for each cell? It would be great if link path, include path, and flags can be configured dynamically.

**Comment by spoorcc** [comment]
Currently each cell is a completely separate program. So the flags are per cell as you want.

I've created issue #28 to support multiple cells for 1 program in the future.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SamKChang** [comment]
Thanks for the reply! I followed the README.md to install the package. It seems it is not the updated version, where there is no ```_filter_magics``` function defined. I think the version on PIPY should be updated. 

Just to play around, I copy the updated files from this repository to the package path (also the ../resource folder for master.c) and define magic flags with
```
//%cflags:-lfftw3
//%cflags:-lm
// some fftw3 code
```
And the cell executes without problem.
