### ISSUE TITLE
show line number in source code

### ISSUE THREAD

**Issue by sconde** [brendan-rius/jupyter-c-kernel#33]

**Comment by brendan-rius** [comment]
This is a Jupyter thing.
Here is the shortcut to toggle line numbers : CTRL+M - L (press CTRL+M, then release and press L)

**Comment by spoorcc** [comment]
Is the regular method for showing line numbers in jupyter not working? ([described here](https://stackoverflow.com/questions/10979667/showing-line-numbers-in-ipython-jupyter-notebooks#10986483)) 

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
