### ISSUE TITLE
undefined symbol: main

### ISSUE THREAD

**Issue by tbhaxor** [brendan-rius/jupyter-c-kernel#63]
I have installed the kernel with `--sys-prefix` argument and now its listed on `jupyter kernelspec list`

**Screen Shot**

![image](https://user-images.githubusercontent.com/28386721/57570795-a99fa480-7423-11e9-910e-9597ccc2c593.png)

**Comment by Fulguritus** [comment]
This is to be expected. Please either add the `-c` compile option, or add an empty main function: 
```
#include <stdio.h>

int main () {}
```

**Comment by tbhaxor** [comment]
@Fulguritus  can i use c kernel like xeus-cling ?
means no `int main`

and where to use add -c option ?

**Comment by Fulguritus** [comment]
In this case I would like to point you to https://github.com/QuantStack/xeus-cling . This kernel is for C - not C++.
