### ISSUE TITLE
kernel does not show up after install on jupyterhub/lab

### ISSUE THREAD

**Issue by aymaliev** [brendan-rius/jupyter-c-kernel#69]
Hello

On CentOS I have JupyterHub.

**install_c_kernel** returns: _Installing IPython kernel spec_
And then, there is no C kernel in the notebook - neither in the /lab interface, nor in the /tree interface. The only kernel is Python3.

gcc, python3, jupyter and pip are all in place. 

What could be the problem?

**Comment by wanwangzhiwang** [comment]
me too！
What could be the problem？

**Comment by tinmarino** [comment]
Have you seen #52 ? I quote : 
* `install_c_kernel --sys-prefix` instead of `install_c_kernel`

![jupyter_c_1](https://user-images.githubusercontent.com/6123962/70857793-ebba2880-1ed3-11ea-929c-ae9db597191c.png)

**Comment by aymaliev** [comment]
Thank you, @tinmarino . This solves it.
My apologies for not finding it before posting an issue.

**Comment by Kiottuze** [comment]
Hello

I have this problem on windows, installed the c kernel with docker, but it does not appear in jupyter lab/notebook

what could be the problem?

its my first time posting an issue, dont know if its ok to post on a closed thread, sorry
