### ISSUE TITLE
Kernel dies under JupyterHub 

### ISSUE THREAD

**Issue by sdd3** [brendan-rius/jupyter-c-kernel#8]
Kernel is identified by jupyterhub but fails to start

```
Dead kernel

The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened
```.

**Comment by ryukinix** [comment]
Hmmm, that message, I already saw her. This comes from the Jupyter's frontend, right? You can copy  the output of `kernel` backend running in your terminal and paste here? Ohhh... but you are using `jupyterhub`, complete this task with this may be more harder .

Probably is something related with the `kernel.json`. I remember to suffering with some similar thing with other kernel... OW, I remember. Was with cl-jupyter kernel (Common Lisp). But sadly I could not fix it — was a deep problem with the Common Lisp code.

**Comment by sdd3** [comment]
Here's the relevant section of the log file 

```
[D 2016-04-29 09:21:07.342 user1 kernelspec:132] Found kernel c_spec in /usr/local/share/jupyter/kernels
[D 2016-04-29 09:21:07.343 user1 kernelspec:139] Native kernel (python3) available from /usr/lib/python3.4/site-packages/ipykernel/resources
[D 2016-04-29 09:21:07.343 user1 manager:241] Starting kernel: ['python', '-m', 'c_kernel', '-f', '/home/user1/.local/share/jupyter/runtime/kernel-09670651-81\
9e-4c67-b185-6b3b8cfd99f5.json']
[D 2016-04-29 09:21:07.352 user1 connect:451] Connecting to: tcp://127.0.0.1:48218
[I 2016-04-29 09:21:07.356 user1 kernelmanager:89] Kernel started: 09670651-819e-4c67-b185-6b3b8cfd99f5
[D 2016-04-29 09:21:07.357 user1 kernelmanager:90] Kernel args: {'kernel_name': 'c_spec', 'cwd': '/home/user1/notebooks'}
[D 2016-04-29 09:21:07.362 user1 log:47] 201 POST /user/user1/api/sessions (95.44.124.67) 32.97ms
[D 2016-04-29 09:21:07.365 user1 log:47] 200 GET /user/user1/api/contents/example-notebook.ipynb/checkpoints?_=1461922400972 (95.44.124.67) 1.95ms
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
      "__main__", fname, loader, pkg_name)
        File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
            exec code in run_globals
              File "/usr/lib/python2.7/site-packages/c_kernel/__main__.py", line 1, in <module>
                  from ipykernel.kernelapp import IPKernelApp
                  ImportError: No module named ipykernel.kernelapp

```

**Comment by ryukinix** [comment]
HMMMMMMMMMM, nice got. Is something with `jupyter` || `ipython` version. I see you are executing the jupyter with `python2`. I don't have tested that kernel using `python2`. Put here your `jupyter` || `ipython` version.

**Comment by sdd3** [comment]
Everything should be python3 but the checkpointing does seem to be forcing python2 

> ipython --version
> 4.1.2
> jupyter --version
> 4.1.0

**Comment by sdd3** [comment]
Thanks for the suggestion of looking at `kernel.json` ryukinix. I edited its argument list from `python` to `python3` and all seems ok 


```
{
  "argv": [
    "python3",
    "-m",
    "c_kernel",
    "-f",
    "{connection_file}"
  ],
  "display_name": "C",
  "language": "c"
}

```

**Comment by ryukinix** [comment]
Wow! Congratulations, really nice you got it! I'm be glad to helped you in investigating! : D

Maybe the @brendan-rius can forces the execution of python3 at `kernel.json` like you does now. That way we avoid other people suffering with it later. All debian/ubuntu still for default yet `python` -> pointing to `python2`. So the targets will be large.  I think put `python3` at specification doesn't affect already users whose uses python -> python3 as well.

Other more generic solutions is making kernel compliant with python2.

**Comment by brendan-rius** [comment]
The project now requires Python 3 :) (see 110b31e505cafd5eddb4cd1bae1631553b64eac0)

**Comment by HunterYIboHu** [comment]
I edited the content of `kernel.json`, and now it is:
```
{
  "argv": [
    "python",
    "-m",
    "jupyter_c_kernel",
    "-f",
    "{connection_file}"
  ],
  "display_name": "C",
  "language": "c"
}
```
But I still found the error like this:
```
[E 08:19:48.474 NotebookApp] Failed to run command:
   ['python3', 
    '-m',
     'jupyter_c_kernel', 
    '-f',
     'C:\\Users\\HuYibo\\AppData\\Roaming\\jupyter\\runtime\\kernel-8b2b70bf-5c43-40b2-a64f-a063f75ad690.json'
]
```
In my computer, the truly python3's command is 'python', not 'python3' :(
@brendan-rius
